-- CREATE TABLES

CREATE TABLE IF NOT EXISTS user (
    id       	INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name     	VARCHAR (200) NOT NULL,
    data_create DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
    id       	INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    user_id     INTEGER NULL,
    price       REAL NULL,
    data_create DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(user_id) REFERENCES user(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
    id       	INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    user_id     INTEGER NULL,
    comment     TEXT NOT NULL,
    FOREIGN KEY(user_id) REFERENCES user(id) ON DELETE CASCADE
);

-- ADD FOREIGN KEYS